"""empty message

Revision ID: 677a92b0793e
Revises: 607eeef8dfa0
Create Date: 2020-05-13 17:31:20.900451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a92b0793e'
down_revision = '607eeef8dfa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
